<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="4.475" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2023-02-11T09:54:52" tests="0" file="cypress\e2e\search.cy.js" time="0.000" failures="0">
  </testsuite>
  <testsuite name="search for books" timestamp="2023-02-11T09:54:52" tests="1" time="4.407" failures="1">
    <testcase name="search for books &quot;before each&quot; hook for &quot;should return one book with title Agile Testing&quot;" time="0.000" classname="&quot;before each&quot; hook for &quot;should return one book with title Agile Testing&quot;">
      <failure message="The following error originated from your application code, not from Cypress.

  &gt; getProducts is not defined

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `search for books`" type="ReferenceError"><![CDATA[ReferenceError: The following error originated from your application code, not from Cypress.

  > getProducts is not defined

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `search for books`
    at <unknown> (http://127.0.0.1:8080/:27:21)]]></failure>
    </testcase>
  </testsuite>
</testsuites>